### ISSUE TITLE
Interface keywords no longer used

### ISSUE THREAD

**Issue by bergwerf** [platelk/vscode-dart#4]
I'd like to use `interface` as field name without it being highlighted. See line https://github.com/platelk/vscode-dart/blob/03f7cd46d552a2ede0b4013de3aa60c507de01d0/syntaxes/dart.json#L241.

The `interface` keyword was removed ~5 years ago, see: http://news.dartlang.org/2012/06/proposal-to-eliminate-interface.html.

**Comment by platelk** [comment]
Hi,

Sorry but this extension is deprecated and you should use [DartCode](https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code)

**Comment by bergwerf** [comment]
Ah, sorry, I ended up reporting this on the wrong repo (I actually use Dart-Code).
